#!/usr/bin/env python
#JSON {"lot": "UHF/cc-pVDZ",
#JSON  "scf": "PlainSCFSolver",
#JSON  "linalg": "CholeskyLinalgFactory",
#JSON  "difficulty": 2,
#JSON  "description": "Basic UHF example with Cholesky decomposition of the ERI"}

from horton import *  # pylint: disable=wildcard-import,unused-wildcard-import


# Load the coordinates from file.
# Use the XYZ file from HORTON's test data directory.
fn_xyz = context.get_fn('test/methyl.xyz')
mol = IOData.from_file(fn_xyz)

# Create a Gaussian basis set
obasis = get_gobasis(mol.coordinates, mol.numbers, 'cc-pVDZ')

# Create a linalg factory
lf = DenseLinalgFactory(obasis.nbasis)

# Compute Gaussian integrals
olp = obasis.compute_overlap(lf)
kin = obasis.compute_kinetic(lf)
na = obasis.compute_nuclear_attraction(mol.coordinates, mol.pseudo_numbers, lf)
er = obasis.compute_electron_repulsion(lf)

# Create alpha orbitals
exp_alpha = lf.create_expansion()
exp_beta = lf.create_expansion()

# Initial guess
guess_core_hamiltonian(olp, kin, na, exp_alpha, exp_beta)

# Construct the restricted HF effective Hamiltonian
external = {'nn': compute_nucnuc(mol.coordinates, mol.pseudo_numbers)}
terms = [
    UTwoIndexTerm(kin, 'kin'),
    UDirectTerm(er, 'hartree'),
    UExchangeTerm(er, 'x_hf'),
    UTwoIndexTerm(na, 'ne'),
]
ham = UEffHam(terms, external)

# Decide how to occupy the orbitals (5 alpha electrons, 4 beta electrons)
occ_model = AufbauOccModel(5, 4)

# Converge WFN with plain SCF
scf_solver = PlainSCFSolver(1e-6)
scf_solver(ham, lf, olp, occ_model, exp_alpha, exp_beta)

# Assign results to the molecule object and write it to a file, e.g. for
# later analysis
mol.title = 'UHF computation on methyl'
mol.energy = ham.cache['energy']
mol.obasis = obasis
mol.exp_alpha = exp_alpha
mol.exp_beta = exp_beta

# useful for visualization:
mol.to_file('methyl.molden')
# useful for post-processing (results stored in double precision)
mol.to_file('methyl.h5')

# CODE BELOW IS FOR horton-regression-test.py ONLY. IT IS NOT PART OF THE EXAMPLE.
rt_results = {
    'energy': ham.cache['energy'],
    'exp_alpha': exp_alpha.energies,
    'exp_beta': exp_beta.energies,
    'nn': ham.cache["energy_nn"],
    'kin': ham.cache["energy_kin"],
    'ne': ham.cache["energy_ne"],
    'ex': ham.cache["energy_x_hf"],
    'hartree': ham.cache["energy_hartree"],
}
# BEGIN AUTOGENERATED CODE. DO NOT CHANGE MANUALLY.
import numpy as np  # pylint: disable=wrong-import-position
rt_previous = {
    'nn': 9.0797849426636361,
    'energy': -39.554863031594934,
    'ne': -109.66989167408859,
    'ex': -6.150578955382695,
    'exp_alpha': np.array([
        -11.261173936822926, -0.92269777217837667, -0.55507865679849855,
        -0.55507864413068664, -0.38566618064988112, 0.18000169912997199,
        0.2588787367152478, 0.25887875426095569, 0.62056366507437566, 0.62056374522046753,
        0.6652930621670986, 0.6665027111404217, 0.86199475715969054, 0.86199479856105876,
        1.0385302053758392, 1.1755536290788346, 1.1755536661460848, 1.5830020898248665,
        1.6685937625602707, 1.6685939277149389, 1.7097534185388419, 1.8208132769560383,
        2.0694337081810783, 2.0694337151175661, 2.2777640361118729, 2.2777641824311932,
        2.6335291121739273, 2.7182730880363635, 2.7182732510209342
    ]),
    'hartree': 27.9620669215954,
    'exp_beta': np.array([
        -11.235333850494188, -0.82602661058894977, -0.54105216781007981,
        -0.54105216145890767, 0.14324601968237408, 0.1987475791012705,
        0.26771035130193027, 0.26771036839318413, 0.62291244059962581,
        0.62291251825959393, 0.70499609404730001, 0.81625192779197497,
        0.87777073404291339, 0.8777707758608877, 1.0782023109444627, 1.2391367209642845,
        1.2391367634561543, 1.5768917882308719, 1.6727666631845952, 1.672766824303985,
        1.7865645902784462, 1.8299308715123448, 2.1018167293915715, 2.1018167354135744,
        2.2809601163539899, 2.2809602600745253, 2.6386354482233645, 2.7281741197847178,
        2.7281742830148143
    ]),
    'kin': 39.22375573361731,
}
