{% set version = "2.3.0" %}

package:
  name: horton 
  version: {{ version }}

source:
  path: ..

build:
  number: 3
  binary_relocation: true

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }}
    - cmake
    - make
    - git
  host:
    - python
    - numpy
    - scipy
    - cython
    - h5py
    - matplotlib
    - libxc
    - libint <2.8
    - pip
  run:
    - python
    - numpy
    - scipy
    - h5py
    - matplotlib
    - libxc
    - libint <2.8
    - cython
test:
  requires:
    - nose
  imports:
    - horton
  commands:
    - nosetests -v horton
  

about:
  summary: "Helpful Open-source Research TOol for N-fermion systems"
  license: GPLv3.0
  home: https://github.com/theochem/horton
