#!/usr/bin/env python
# -*- coding: utf-8 -*-
# HORTON: Helpful Open-source Research TOol for N-fermion systems.
# Copyright (C) 2011-2016 The HORTON Development Team
#
# This file is part of HORTON.
#
# HORTON is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# HORTON is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>
#
# --
"""Check commits for bad habits. Can be used as pre-commit when no arguments are given."""


import argparse
import subprocess
import sys


def main():
    """Main program."""
    ancestor = parse_args()
    check_commits(ancestor)


def parse_args():
    """Determine which commits to check, from command-line args.

    When no arguments are given, the index (commit to be made) will be checked. Otherwise,
    all commits up to the ancestor are checked.
    """
    parser = argparse.ArgumentParser(description='Check basic formatting conventions in commits.')
    parser.add_argument('ancestor', type=str, default=None, nargs='?',
                        help='The ancestor up to which to check the commits. When not '
                             'given, the index is checked.')
    args = parser.parse_args()
    return args.ancestor


def check_commits(ancestor):
    """Check commits up to ancestor for bad habits.

    When ancestor is None, the staged files are checked.
    """

    # If all goes well, the exit code remains zero.
    result = 0

    if ancestor is None:
        print 'Checking for bad habits in files to be committed ...'
        diff_args = ['--cached']
    else:
        print 'Checking for bad habits in commits up to {} ...'.format(ancestor)
        lines = subprocess.check_output(
            ['git', 'log', '%s..HEAD' % ancestor, '--pretty=oneline', '--color=never'],
            stderr=subprocess.STDOUT).decode("utf-8").splitlines()

        # Parse the output
        commit_ids = []
        for line in lines:
            commit_id = line.partition(' ')[0]
            commit_ids.append(commit_id)
        commit_ids.append(ancestor)

        # Define the ranges to be checked with git diff
        diff_args = []
        for i in xrange(len(commit_ids) - 1):
            diff_args.append('{}..{}'.format(commit_ids[i], commit_ids[i+1]))

    # Loop over all commits and check them:
    for diff_arg in diff_args:
        if ancestor is not None:
            print 'Checking diff {}'.format(diff_arg)
        # Get a list of files in the diff.
        filenames = subprocess.check_output(
            ['git', 'diff', '--name-only', diff_arg],
            stderr=subprocess.STDOUT).decode("utf-8").splitlines()

        # Check all files in the diff.
        for fn in filenames:
            # Get the diff for this file.
            diff_lines = subprocess.check_output(
                ['git', 'diff', '--color=never', diff_arg, '--', fn],
                stderr=subprocess.STDOUT).decode("utf-8").splitlines()
            # Run some tests on the diff.
            for line in diff_lines:
                if line.startswith('diff') or line.startswith('index') or \
                   line.startswith('-') or line.startswith('+++'):
                    pass
                elif line.startswith('@@'):
                    line_number = line.split()[2]
                    if ',' in line_number:
                        line_number = line_number.partition(',')[0]
                    line_number = int(line_number)
                elif line.startswith('+'):
                    if '\t' in line:
                        print '   Tab                   {}:{}'.format(fn, line_number)
                        result = 1
                    if line.endswith(' '):
                        print '   Trailing whitespace   {}:{}'.format(fn, line_number)
                        result = 1
                    if fn.startswith('horton') and 'print' in line:
                        print '   print command         {}:{}'.format(fn, line_number)
                        result = 1
                    line_number += 1
                elif line.startswith(' '):
                    line_number += 1
            # Get the entire file in the diff.
            if ancestor is None:
                commit_id = ''
            else:
                commit_id = diff_arg.partition('..')[-1]
            new_contents = subprocess.check_output(
                ['git', 'show', commit_id + ':' + fn],
                stderr=subprocess.STDOUT).decode("utf-8")
            # Check for other bad things.
            if '\r' in new_contents:
                print '   \\r                    {}'.format(fn)
                result = 1
            if new_contents.endswith('\n\n'):
                print '   Trailing newlines     {}'.format(fn)
                result = 1
            if not new_contents.endswith('\n'):
                print '   Missing last newline  {}'.format(fn)
                result = 1

        if ancestor is None:
            # Look for untracked files in important directories
            status_lines = subprocess.check_output(
                ['git', 'status', '-u', 'data', 'horton', 'doc', 'scripts', 'tools', '--porcelain'],
                stderr=subprocess.STDOUT).decode("utf-8").splitlines()
            for status_line in status_lines:
                if status_line.startswith('??'):
                    fn = status_line[3:]
                    print '   Untracked file        {}'.format(fn)
                    result = 1

    # Stop process with appropriate exit code.
    if result != 0:
        print 'Commit failed. Please, clean up and try again.'
    else:
        print 'OK.'
    sys.exit(result)


if __name__ == '__main__':
    main()
